[package]
name = "airborne-oxide"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.0"
panic-halt = "0.2.0"
stm32f4xx-hal = { version = "0.21.0", features = ["stm32f405"] }
defmt = "0.3"
defmt-rtt = "0.4"


[dev-dependencies]
cortex-m-semihosting = "0.5.0"
defmt-test = "0.3"